apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: http1
      protocol: TCP
      name: http1
    - port: {{ .Values.service.port2 }}
      targetPort: http2
      protocol: TCP
      name: http2
  selector:
    {{- include "sonarqube.selectorLabels" . | nindent 4 }}
